config/routes.rb
Authentication::Application.routes.draw do

  resources :users, except: [:index, :show, :destroy]
  resource  :session, only:  [:new, :create, :destroy]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :products, only: [:show, :update, :index] do
    resources :product_reviews, except: :index
  end
  resources :companies, only: :show
  resources :notifications, only: [:index, :destroy]
  resources :all_logins, only: [:index, :show]

  resource :admin, only: :show
  namespace :admin do
    resource :company
    resources :people, except: :show do
      get :invites, on: :collection
    end
    resources :products
    resources :partners
    resources :partner_products
    resources :reports, only: [:index, :show]
  end

  root :to => 'dashboard#index'
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/all_logins_controller.rb
class AllLoginsController < ApplicationController
  layout false

  def index
    @companies = Company.starts_with(params[:char]).includes(:users).page(params[:page]).per(5)
  end

  def show
    user = User.find(params[:id])
    cookies[:auth_token] = user.auth_token
    user.logins.create
    redirect_to :root
  end

end

app/views/all_logins/index.html.slim
doctype html
html
  = render 'layouts/head'
  body
    .container
      h2 All Logins
      .alphabets_index_action_links
        - alphabets = ('a' .. 'z').to_a
        - alphabets.each do |char|
          = link_to char, all_logins_path(char: char)
          '
        = link_to 'ALL', all_logins_path
      = paginate @companies
      .all_logins
        - @companies.each do  |company|
          .column
            h4= link_to company.name, all_login_path(company.users.first)
            ul
              - User::ROLES.each_with_index do |v, i|
                li
                  =' t("roles.#{v}").pluralize << ':'
                  - company.users.select { |u| u.role_id == i }.each do |u|
                    =' link_to u.name, all_login_path(u)
      = paginate @companies