config/routes.rb
Authentication::Application.routes.draw do

  resources :users, except: [:index, :show, :destroy]
  resource  :session, only:  [:new, :create, :destroy]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :products, only: [:show, :update, :index] do
    resources :product_reviews, except: :index
  end
  resources :companies, only: :show
  resources :notifications, only: [:index, :destroy]
  resources :all_logins, only: [:index, :show]

  resource :admin, only: :show
  namespace :admin do
    resource :company
    resources :people, except: :show do
      get :invites, on: :collection
    end
    resources :products
    resources :partners
    resources :partner_products
    resources :reports, only: [:index, :show]
  end

  root :to => 'dashboard#index'
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < AdminsController

  add_breadcrumb I18n.t('breadcrumbs.administration'), :admin_path
  add_breadcrumb I18n.t('breadcrumbs.manage_people'), :admin_people_path, except: :index

  def index
    @people = company.users.activated.page(params[:page])
  end

  def new
    @users = [company.users.build(role_id: User::ROLES.index(User::EMPLOYEE))]
  end

  def create
    @users = []
    params[:users].each do |attrs|
      @users << current_user.class.new(attrs)
    end
    company.users << @users
    if company.valid?
      UserNotifier.perform_async(:invite, user_ids: @users.map(&:id), admin_id: current_user.id)
      redirect_to invites_admin_people_path, notice: I18n.t('flash.user.invite_sent')
    else
      render :new
    end
  end

  def update
    user = company.users.find(params[:id])
    user.update_attributes(role_id: params[:role_id])
    flash.now[:notice] = t('flash.user.role_updated')
  end

  def destroy
    @user = company.users.find(params[:id]).destroy
    if @user.activated?
      redirect_to admin_people_path, notice: t('flash.user.deleted', name: @user.name)
    else
      redirect_to invites_admin_people_path, notice: t('flash.user.invite_canceled')
    end
  end

  def invites
    @users = company.users.invited
  end

  private

  def company
    @company ||= current_user.company
  end

end

app/views/admin/people/_invite.html.slim
tr
  td= invite.name
  td= invite.job
  td= invite.email
  td= invite.role
  td= t(".invited_#{invite.activated?}")
  td= link_to t('cancel'), admin_person_path(invite), method: :delete, confirm: t('.delete_message'), 'data-title' => t('confirm_delete')

app/views/admin/people/_person.html.slim
tr
  td= person.name
  td= person.email
  td= person.job
  - if current_user == person
    td= I18n.t("roles.#{person.role}")
  - else
    td= select :user, :role, User::ROLES.map { |k, v| [I18n.t("roles.#{v}"), k]}, { selected: person.role_id }, class: 'role-select', 'data-url' => admin_person_path(person)
  td= link_to t('delete'), admin_person_path(person), method: :delete, confirm: t('.delete_message'), 'data-title' => t('confirm_delete') unless current_user == person

app/views/admin/people/index.html.slim
- if @people.blank?
  = t('.no_people')
- else
  table.table.table-hover.table-striped
    thead
      tr
        th= t('.name')
        th= t('.email')
        th= t('.job')
        th= t('.role')
        th= t('.actions')
    tbody
      = render partial: 'person', collection: @people

app/views/admin/people/invites.html.slim
= content_for :title_links do
  ul.unstyled.inline.text-right
    li= link_to t('.manage_people'), admin_people_path
    li= link_to t('.invite_employees'), new_admin_person_path

- if @users.blank?
  = t('.no_invites')
- else
  table.table.table-hover.table-striped
    thead
      tr
        th= t('.name')
        th= t('.job')
        th= t('.email')
        th= t('.role')
        th= t('.status')
        th
    tbody
      = render partial: 'invite', collection: @users

app/views/admin/people/new.html.slim
.row-fluid
  .span7
    = t('.invite_employees')
  .span5.text-center
    = t('.used')
    h4.gray= "#{@company.users.count} / #{@company.employee_limit}"
    = t('.seats')

= simple_form_for :users, url: admin_people_path, html: { class: 'form-inline' } do |form|
  ol
    - @users.each do |user|
      = form.fields_for '', user do |f|
        li.row-fluid
          = f.input :first_name, input_html: { class: 'input-medium' }, wrapper_html: { class: 'span2'}
          = f.input :last_name, input_html: { class: 'input-medium' }, wrapper_html: { class: 'span2'}
          = f.input :email, input_html: { class: 'input-medium' }, wrapper_html: { class: 'span2'}
          = f.input :job, input_html: { class: 'input-medium' }, wrapper_html: { class: 'span2'}
          = f.input :role_id, collection: User::ROLES.map { |r| [I18n.t("roles.#{r}"), User::ROLES.index(r)]}, include_blank: false, input_html: { class: 'input-medium' }, wrapper_html: { class: 'span2'}
          .span2
            = f.input :invited, as: :hidden, input_html: { value: true }
            =link_to t('remove'), '', class: 'remove-user hide'
    = link_to t('.add_user'), '', class: 'add-user'
  .span2.offset10
    = form.button :submit, t('.invite_users')

app/views/admin/people/update.js.erb
$('body .notification').slideUp(function(){ $(this).remove() })
$("<%= j(render partial: 'layouts/messages') %>").prependTo('body').hide().slideDown();