config/routes.rb
Authentication::Application.routes.draw do

  resources :users, except: [:index, :show, :destroy]
  resource  :session, only:  [:new, :create, :destroy]
  resources :password_resets, except: [:index, :show, :destroy]
  resources :products, only: [:show, :update, :index] do
    resources :product_reviews, except: :index
  end
  resources :companies, only: :show
  resources :notifications, only: [:index, :destroy]
  resources :all_logins, only: [:index, :show]

  resource :admin, only: :show
  namespace :admin do
    resource :company
    resources :people, except: :show do
      get :invites, on: :collection
    end
    resources :products
    resources :partners
    resources :partner_products
    resources :reports, only: [:index, :show]
  end

  root :to => 'dashboard#index'
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/product.rb
class Product < ActiveRecord::Base
  include BaseProduct
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :reviews, class_name: ProductReview, dependent: :delete_all
  has_many :ratings, class_name: ProductRating, dependent: :delete_all
  has_one  :draft,   class_name: ProductDraft, dependent: :destroy
  belongs_to :company

  scope :search, ->(q) { where(['name LIKE ?', "%#{q}%"]) }
  scope :sorted, -> { includes(:draft).order('product_drafts.status DESC, products.name ASC') }

  def rate_it!(user, score)
    r = ratings.find_or_initialize_by(user_id: user.id)
    r.update_attributes(score: score)
    reload
  end

  def user_rating(user)
    @rate ||= ratings.find_by_user_id(user.id)
    return @rate.score if @rate
    0
  end

  def user_review_id(user)
    review = reviews.find_by_user_id(user.id)
    review.id if review
  end

  def product_id
    id
  end

  def approve!
    publish! unless published?
  end

  def product_status
    return draft.status if draft
    status
  end

  def draft_or_build
    return draft if draft
    build_draft(attributes)
    draft.icon = icon unless draft.icon?
    draft.image = image unless draft.image?
    draft.banner = banner unless draft.banner?
    draft.software = software unless draft.software?
    draft.images = images.map(&:dup)
    draft
  end

  private

  def delete_associations
    images.delete_all
    videos.delete_all
    resources.delete_all
    pricings.delete_all
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminsController

  before_filter :authorize, :require_partner

  add_breadcrumb I18n.t('breadcrumbs.administration'), :admin_path

  def index
    @products = current_user.company.products.page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.company.products.build(params[:product])
    if @product.save
      if params[:save]
        flash.now[:notice] = I18n.t('flash.product.saved')
        render :edit
      else
        @product.submit!
        ProductNotifier.perform_async(:submitted, user_id: current_user.id, product_id: @product.product_id)
        redirect_to admin_products_path, notice: I18n.t('flash.product.submitted')
      end
    else
      render :new
    end
  end

  def show
    product
    render 'products/show', layout: 'dashboard'
  end

  def edit
    redirect_to admin_products_path, alert: I18n.t('flash.product.pending') if product.pending?
  end

  def update
    if product.update_attributes(params[:product])
      if params[:save]
        flash.now[:notice] = I18n.t('flash.product.saved')
        render :edit
      else
        product.submit!
        ProductNotifier.perform_async(:submitted, user_id: current_user.id, product_id: @product.product_id)
        redirect_to admin_products_path,  notice: I18n.t('flash.product.submitted')
      end
    else
      render :edit
    end
  end

  def destroy
    @product = current_user.company.products.friendly.find(params[:id])
    if @product.published?
      @product.retract!
      ProductNotifier.perform_async(:retracted, user_id: current_user.id, product_id: @product.id)
    end
    redirect_to admin_products_path
  end

  private

  def product
    product = current_user.company.products.friendly.find(params[:id])
    if !product.published?
      @product = product
    else
      @product = product.draft_or_build
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  layout 'dashboard'

  def index
    @products  = Product.search(params[:search])
    @categories = Category.all
  end

  def show
    @product = Product.where(slug: params[:id]).includes(reviews: :user).first
    if current_user
      @reviewed = @product.reviews.find_by_user_id(current_user.id)
    end
  end

  def update
    @product = Product.friendly.find(params[:id])
    @product.rate_it!(current_user, params[:score])
  end

end

app/views/products/_rating.html.slim
.product-rating
  h4.title= t('.customer_ratings')
  - if current_user
    h5.title= t('.your_rating')
    .user-rating
      span.user
        - 5.downto(1) do |i|
          = link_to '', product_path(@product, score: i), method: :put, remote: true, class: (@product.user_rating(current_user) >= i ? 'icon-star icon-2x' : 'icon-star-empty icon-2x')
  - unless @product.ratings.blank?
    .average
      h5.title= t('.average_rating')
      - 5.times do |i|
        i.icon-2x class=((i < @product.rating_average.to_i) ? 'icon-star' : 'icon-star-empty')
    .total
      - 5.downto(1) do |i|
        .row-fluid
          .span5.offset1
              = render_rating(i)
          .span3
            = @product.ratings.select { |p| p.score == i }.count

app/views/products/index.html.slim
.products
  hr.nav-border
  = render partial: 'layouts/search'
  .container.row-fluid
    .search-panel
      .criteria
        h4.pull-left.title= t('.search_results', count: @products.count)
        h4.pull-left.icon-tags
        h6.pull-left.title= t('.criteria')
        ul.pull-left.search-categories
          - if platforms = params[:platforms]
            - platforms.each do |platform|
              ='
              li.label.label-info id="label_platform_#{platform}"
                = t("platform.#{platform}")
                label for="platform_#{platform}" ×
          - if ids = params[:category_ids]
            - ids.each do |id|
              ='
              li.label.label-info id="label_category_#{id}"
                = @categories.find(id).name
                label for="category_#{id}" ×
      .clearfix
      = form_tag products_path, method: :get do
        ul.unstyled.filters
          li.pull-left.first
            .input-append
              = text_field_tag :search, params[:search]
              = button_tag class: 'btn' do
                i.icon-search
          li.pull-left.platforms-dropdown
            b
              = t('os')
              i.icon-sort
            .platforms.hide
              = label_tag 'platform_android', class: 'checkbox' do
                = check_box_tag 'platforms[]', 'android', params[:platforms] && params[:platforms].include?('android'), id: "platform_android"
                = t('platform.android')
              = label_tag 'platform_ios', class: 'checkbox' do
                = check_box_tag 'platforms[]', 'ios', params[:platforms] && params[:platforms].include?('ios'), id: "platform_ios"
                = t('platform.ios')
          li.pull-left.categories-dropdown
            b
              = t('categories')
              i.icon-sort
            .categories.hide
              - @categories.each do |c|
                = label_tag "category_#{c.id}", class: 'checkbox' do
                  = check_box_tag "category_ids[]", c.id, params[:category_ids] && params[:category_ids].include?(c.id.to_s), id: "category_#{c.id}"
                  = c.name
              .clearfix
          li.last.pull-right
          .clearfix
    .row-fluid
      .span12
        #search-carousel.main-carousel.carousel.slide data-interval=""
          .carousel-inner
            - @products.each_slice(24).with_index do |products, i|
              = content_tag(:div, class: i.zero? ? 'item active' : 'item') do
                = render partial: 'dashboard/basic_product', collection: products, as: :product
          a.carousel-control.left href="#search-carousel" data-slide="prev" &lsaquo;
          a.carousel-control.right href="#search-carousel" data-slide="next" &rsaquo;

app/views/products/show.html.slim
.product
  hr.nav-border
  = render partial: 'layouts/search'
  .container.row-fluid
    .span12
      h1.page-title= @product.name
    .span2
      p
        = image_tag(@product.icon.url)
      p
        b=' t('.company')
        = link_to @product.company.name, company_path(@product.company)
      = render partial: 'products/rating'
    .span8
      .product-info
        p.product-description= @product.description
        .tabbable
          ul.nav.nav-tabs
            li.active
              a href='#tab1' data-toggle='tab'= t('.summary')
            li
              a href='#tab2' data-toggle='tab'= t('.features')
            li
              a href='#tab3' data-toggle='tab'= t('.support')
          .tab-content
            #tab1.tab-pane.active
              p= @product.summary
            #tab2.tab-pane
              p= @product.features
            #tab3.tab-pane
              p= @product.support
        .reviews
          h5.page-title
            = t('.customer_reviews')
            - if current_user && !@reviewed
              = link_to t('.write_review'), new_product_product_review_path(@product), remote: true, class: 'pull-right'
          ul.reviews-list
            = render partial: 'product_reviews/product_review', collection: @product.reviews
    .span2

app/views/products/update.js.erb
$('.product-rating').replaceWith("<%= j(render partial: 'rating') %>")
$('#product_review_' + "<%= @product.user_review_id(current_user) %>" + ' .user-rating').html("<%= j(user_product_rating(@product, current_user)) %>")